### PR TITLE
WIP - Add Arm Support

### PR DESCRIPTION
**Pull request by andrewc910**
This is a PR for adding ARM support for elementary's build process. Most of the changes lie in the terraform.conf, & auto/config files. I added new dependencies to be installed in the build file. These are for qemu to work. We can easily make it that these qemu packages are only installed if we are compiling for arm.

**What has changed:**
- Several new variables in terraform.conf
- Several new options on the `lb config` command for said variables
- New dependencies for building
- Documentation for terraform - left little notes on what the values should be for each arch. I also converted ONE elementary terraform file to the new format for review. I didn't test the build and can do so if requested.

**What works:**
- It builds...
- All elementary packages install except for the app center. I left a todo in the terraform.conf file

**What doesn't work:**
- Booting: something to do with the bootloader - there is no boot folder after writing the image to a sd card
- Casper hook - had to comment it out for the time being
- xz compression? File comes out as 'img' and not 'img.xz'
- The last few lines in build transferring the file to 'builds' - it looks for a file with an extension 'hybrid.iso' but that's an easy fix and doesn't stop the build

**Things to discuss:**
- Benefits of rpi optimized kernel
- Grub, u-boot(used by ubuntu for arm) or rpi bootloader
- terraform new format

**How to run it**
Same as running the main version but use a Debian unstable docker container. Stable doesn't have the version of live build that supports qemu cross building. My arm config is just the "terraform.conf" file.

### CODE REVIEW

**Comment by davidmhewitt** [comment]
Just to let you know, I haven't forgotten about this or been ignoring it. I'm spending some time testing out some ARM builds today using some of the changes you've made here. I'll keep you updated as and when I make progress.

**Comment by andrewc910** [comment]
No worries! I figured you'd get to it when you get it. I've been playing around some more. I have it building 100% of the time but still can't get it boot. Hoping you know a thing or two I don't haha

**Comment by davidmhewitt** [comment]
Got to admit, I've been struggling to make `live-build` produce anything useful for my raspberry pi too, but your changes definitely helped me figure out some parts where I got stuck last time.

Given that the ARM builds don't necessarily need the complexities of hybrid iso images that support both BIOS and UEFI and are signed to boot on secure boot enabled systems, it seems to be proving easier to write a custom shell script that does a debootstrap, installs the elementary packages, installs a raspberry pi specific kernel and assembles this all together into a hybrid fat32/ext4 image with all the raspberry pi specific config/firmware in the right places.

I have a script that does this and produces an image that boots on my RPi, but don't yet have it booting into a graphical environment. I'm going to spend a little while longer on trying to get it to work fully, but I'll clean it up and upload it somewhere in the next day or two so other people can have a play.

**Comment by davidmhewitt** [comment]
I've opened a draft PR here with a build script that successfully builds RPi images (or at least ones that work on my Pi 3B+):
https://github.com/elementary/os/pull/343

There are a number of things to do before it can even be considered usable, nevermind official.

@andrewc910 If you want to help out with any of my TODOs on the other PR, feel free! Otherwise, thanks for the help on this, it certainly gave me the inspiration and kick I needed to look into this properly. I spent a couple of days trying to get `live-build` to work as you have, then got much further in a matter of hours by doing it manually with a custom script.

**Pull request closed without merging**
