### PR TITLE
Create apparmor-profiles.chroot

### PR DESCRIPTION
**Pull request by danirabbit**
Fixes https://github.com/elementary/triage/issues/600

Errors with:

```
Cache read/write disabled: interface file missing. (Kernel needs AppArmor 2.4 compatibility patch.)
Warning: unable to find a suitable fs in /proc/mounts, is it mounted?
Use --subdomainfs to override.
```

### CODE REVIEW

**Comment by teamcons** [comment]
So ive diden a quick look,
Either apparmor isnt enabled, or a kernel parameter is missing

One fix someone found is in the answers :
https://www.reddit.com/r/linuxquestions/comments/12xdwhm/apparmor_doesnt_load_even_though_i_did_everything/

I also found this topic on the not-arch-but-kinda forums
https://forum.artixlinux.org/index.php/topic,2124.0.html
point to arch wiki https://wiki.archlinux.org/title/AppArmor#Installation

one about a pihole, apparmor wasnt awake
https://discourse.pi-hole.net/t/apparmor-reference-in-unbound-guide-clarification-requested/62351

Haha this sounds like fun /s

**Comment by teamcons** [comment]
Btw this is a dirty workaround for the issue - May be good only for the live
> chmod u+s /usr/bin/bwrap

**Comment by davidmhewitt** [comment]
I've changed this to just symlink the profile into the active profiles directory instead of actually trying to load an insert the profile during the iso build (where we're running in Docker in a CI environment, hence the issues with the kernel).

Having the symlink in this directory should make the profile automatically load when we boot ISOs with this symlink in place. Let's try this again and see if the daily ISOs build and have fixed flatpaks.

**Review by davidmhewitt — APPROVED** [review]

**Comment by ryonakano** [comment]
@davidmhewitt I built a daily iso from latest master (97e8eb0b2f3754b0d5428936bb3ca8ab813c1d95) and confirmed it works as expected. Thank you!

VirtualBox_test_25_12_2024_21_22_58

**Comment by teamcons** [comment]
Maybe we could generate a new stable iso ? Since this affects the demo

**Comment by davidmhewitt** [comment]
> Maybe we could generate a new stable iso ? Since this affects the demo

I'm waiting on getting this one in too https://github.com/elementary/os/pull/745

**Pull request merged**
