### PR TITLE
Install elementary apps via apt

### PR DESCRIPTION
**Pull request by meisenzahl**
- [x] Requires https://github.com/elementary/calculator/pull/231
- [x] Requires https://github.com/elementary/camera/pull/247
- [x] Requires https://github.com/elementary/browser/pull/67
- [x] Requires https://github.com/elementary/evince/pull/37
- [x] Requires https://github.com/elementary/seeds/pull/98

### CODE REVIEW

**Comment by meisenzahl** [comment]
Do we also want to install

- org.gnome.Epiphany
- org.gnome.Evince

via apt?

**Comment by danirabbit** [comment]
@meisenzahl Yeah I think so. That would help from Epiphany because we can make sure to install GL as well there instead of here

**Comment by meisenzahl** [comment]
@danirabbit is it enough if I create `deb-packaging` branches?

**Comment by danirabbit** [comment]
@meisenzahl yes! And if you ping me I can set up the launchpad recipes

**Comment by danirabbit** [comment]
Waiting on Seeds: https://code.launchpad.net/~elementary-os/+recipe/seed-metapackages-jammy

**Review by danirabbit — APPROVED** [review]
Seeds is done, let's give it a go!

**Pull request merged**
