### PR TITLE
Prevent override 10-globally-managed-devices.conf overwritten by package update

### PR DESCRIPTION
**Pull request by ryonakano**
We overwrite 10-globally-managed-devices.conf that network-manager package provides when building the iso. However, this conf can be re-overwritten after installation of OS when network-manager package is updated, causing NM no longer manages Ethernet devices as recently reported from some users: https://github.com/orgs/elementary/discussions/658 and https://github.com/elementary/switchboard-plug-network/issues/423.

So, rename our conf to a filename that won't conflict with files provided by network-manager package and make sure it's loaded after and overwrite 10-globally-managed-devices.conf.

### CODE REVIEW

**Comment by davidmhewitt** [comment]
This makes sense, but we should probably check how Ubuntu 24.04 works and manages ethernet devices and why it doesn't work in elementary in case this causes more problems in the future.

**Comment by ryonakano** [comment]
@davidmhewitt (@teamcons) I'm sorry for my late response, I addressed your suggested change and triggered building a daily iso locally before I went to bed, so that the build finishes and I can test the iso when I wake up.

I confirmed it works in the live session:

VirtualBox_test_27_12_2024_09_07_09

and the installed system too:

VirtualBox_test_27_12_2024_09_03_03

**Comment by davidmhewitt** [comment]
> @davidmhewitt (@teamcons) I'm sorry for my late response

No problem! There's no urgency. I just wanted to get this in before we build another stable ISO.

Thank you for your work and investigation here 🙇

**Review by davidmhewitt — APPROVED** [review]

**Comment by danirabbit** [comment]
@davidmhewitt @ryonakano should we be supplying this in default-settings instead so that it can go in an update and not require a new ISO build?

**Comment by davidmhewitt** [comment]
@danirabbit sure, that would make sense I think.

Would need to check the behaviour for how the package installs for someone that's already manually created that file.

**Comment by ealaney** [comment]
> @danirabbit sure, that would make sense I think.
> 
> Would need to check the behaviour for how the package installs for someone that's already manually created that file.

I had this problem on a recent new build and fixed it by manually creating the file. If you need someone to test the package, I can probably do that for you.

**Comment by benbucksch** [comment]
Is this fix shipped already?

I've installed a fresh ElementaryOS, and the Ethernet worked. After I did the update and rebooted, the Ethernet stopped working. The settings UI for Ethernet showed "unmanaged". After I [added](https://www.reddit.com/r/elementaryos/comments/1hdlhn1/comment/m579d0a/)
```
[keyfile] 
unmanaged-devices=none
```
to /etc/NetworkManager/NetworkManager.conf and rebooted (`systemctl restart systemd-networkd` was not sufficient), Ethernet worked again.

**Comment by danirabbit** [comment]
Building a new stable release of elementary OS right now :) Should be on our website soon if everything goes well

**Pull request merged**
