### PR TITLE
Add Raspberry Pi build script

### PR DESCRIPTION
**Pull request by davidmhewitt**
Tested and confirmed working on Pi 400! :tada:

### CODE REVIEW

**Comment by andrewc910** [comment]
Let's drop live-build. I don't believe it is the right tool for this particular problem. 

Have you seen this rpi's official build script? 
 https://github.com/RPi-Distro/pi-gen

This was my second option. I was only using live-build because I thought eOS was only interested in that. Knowing anything is on the table, I think we should really look at rpi's. 

Rpi build scripts are organzied quite well, the bash code is obviously tested from time, and editing would be fairly easy. The scripts and stages are easily digestible since it's just in numeric order. It's also handles cross compilation. I read they somewhere they build on an arm server to forgo cross compilation but eOS isn't forced into using different servers for different builds.

I believe this is what we should be looking at to merge. Let me know what you think!

**Comment by hoytde81** [comment]
Has anyone had any success with merging the two builds?

**Review by meisenzahl — APPROVED** [review]
LGTM

**Comment by davidmhewitt** [comment]
@cassidyjames This has been tested on both a Pi 4 and 400 by both me and @meisenzahl now. Do you want to have final sign off on whether we're going ahead with this or not?

We'll also need to make a PR to the builds site to show these.

**Comment by cassidyjames** [comment]
@davidmhewitt I tested the image a bit and was happy, if you both sign off, let's merge it

**Pull request merged**
