### PR TITLE
Black and white syslinux theme

### PR DESCRIPTION
**Pull request by davidmhewitt**
We currently have a weird blue syslinux bootloader when booting the .iso on legacy BIOS based systems. This PR switches to a black and white theme, screenshots can be found in the thread below.

### CODE REVIEW

**Comment by davidmhewitt** [comment]
@tintou pointed out that we already have a syslinux theme for the iso in the repositories that I'd forgotten about. Due to the differences between Debian and Ubuntu live-build, it's not that easy to integrate this. 

It's forked from the Ubuntu repositories and is the bootloader that shows that little little person symbol at the bottom of the screen for 5 seconds before automatically booting the .iso. If you press a key during that stage, you get into the syslinux menu.

The only things we gain in that syslinux menu are some outdated help files that can be accessed by pressing F1-F10 and a stretched elementary logo if you're using anything other than a 4:3 monitor.

I'll try and pull in a couple of the more useful bits from that theme and update this thread with screenshots. We can make a decision if we want to use this or spend some time trying to integrate the old one.

**Comment by davidmhewitt** [comment]
Current state of this:

image

Above screen can be interrupted by pressing a key and you get the following menu:

image

**Comment by 4jNsY6fCVqZv** [comment]
Thank you for your good work! Just a small thing, but I'm surprised why it says "Booting elementary live disk" instead of "Booting elementary OS live disk". Did you deliberately choose that?
And would it be an idea to add the version name here as well?

**Comment by kgrubb** [comment]
here's how the theme currently looks in the dailies:

Screen Shot 2019-10-23 at 2 19 50 PM

**Comment by davidmhewitt** [comment]
I think we'd concluded in Slack that we wanted to try and keep the original Ubuntu based syslinux theme as it offers language selection functionality that this doesn't. However, as per my comment in #248, I've been struggling to get that to work again using the new Debian `live-build` way of building .iso images. 

Either way, I think this branch improves on the current state of `master` and we'll have to make a decision on whether we continue down this route or try figuring out what's wrong with the old Ubuntu based `live-build` scripts and revert back to those.

**Pull request merged**
